CREATE TABLE `firmy` (
	`ICO` VARCHAR(50) NOT NULL,
	`DIC` VARCHAR(12) NOT NULL,
	`NAZEV` VARCHAR(250) NOT NULL,
	`VZNIK` DATE NOT NULL,
	`ADRESA` VARCHAR(250) NOT NULL,
	`MESTO` VARCHAR(250) NOT NULL,
	`POSLEDNI_UPRAVA` DATE NOT NULL,
	PRIMARY KEY (`ICO`)
) COLLATE='utf8_general_ci';
